-- 生成者Oracle SQL Developer Data Modeler 4.0.3.853
--   时间:        2015-02-11 05:14:35 CST
--   站点:      Oracle Database 10g
--   类型:      Oracle Database 10g




DROP TABLE BHGMS.BHGMS_D_ANNUAL_VACATION CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_APPROVE_NODE CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_APPROVE_PROCESS CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_APPROVE_STATUS CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_APPROVE_TYPE CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_CHANGE_CONTENT CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_CHANGE_CONTENT_SUB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_CHECKIN_STATUS CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_INTIME CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_JOB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_LEADER_BTO CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_RIGHT_MENUITEM CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_RIGHT_SPECITEM CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_D_VACATION_TYPE CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_APPROVE CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_APPROVE_PROCESS CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_APPROVE_VACATION_SUB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_CHECKIN CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_F_VACATION_LIST CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_H_APPROVE CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_H_APPROVE_VACATION_SUB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_H_DIMENSION CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_R_MENUGROUP CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_R_MENUGROUP_OFFICER CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_R_MENUGROUP_ORGAN CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_R_MENUGROUP_SUB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_R_NODE_JOB CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_U_LOGIN CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_U_OFFICER CASCADE CONSTRAINTS ;

DROP TABLE BHGMS.BHGMS_U_ORGAN CASCADE CONSTRAINTS ;

DROP SEQUENCE BHGMS.FA_ID ;

DROP SEQUENCE BHGMS.FC_ID ;

DROP SEQUENCE BHGMS.HA_ID ;

DROP SEQUENCE BHGMS.HD_ID ;

DROP SEQUENCE BHGMS.RMOF_ID ;

DROP SEQUENCE BHGMS.RMO_ID ;

DROP SEQUENCE BHGMS.RM_ID ;

CREATE SEQUENCE BHGMS.FA_ID START WITH 1 INCREMENT BY 1 CACHE 20 ORDER ;

CREATE SEQUENCE BHGMS.FC_ID START WITH 1 INCREMENT BY 1 CACHE 20 ORDER ;

CREATE SEQUENCE BHGMS.HA_ID START WITH 1 INCREMENT BY 1 CACHE 20 ORDER ;

CREATE SEQUENCE BHGMS.HD_ID START WITH 1 INCREMENT BY 1 CACHE 20 ORDER ;

CREATE SEQUENCE BHGMS.RMOF_ID START WITH 1 INCREMENT BY 1 CACHE 1 ORDER ;

CREATE SEQUENCE BHGMS.RMO_ID START WITH 1 INCREMENT BY 1 CACHE 20 ORDER ;

CREATE SEQUENCE BHGMS.RM_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20 ORDER ;

CREATE TABLE BHGMS.BHGMS_D_ANNUAL_VACATION
  (
    DAV_ID        VARCHAR2 (2 BYTE) NOT NULL ,
    DAV_DAYS      NUMBER (2) ,
    DAV_YEARS_MIN NUMBER (2) ,
    DAV_YEARS_MAX NUMBER (2) ,
    DAV_EDITOR    VARCHAR2 (6 BYTE) ,
    DAV_STATUS    CHAR (1 BYTE) ,
    INSERT_TIME   DATE ,
    ALTER_TIME    DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_ANNUAL_VACATION
IS
  '综合管理系统工作年度与年假天数对照表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_ID
IS
  '综合管理系统工作年度与年假天数对照表代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_DAYS
IS
  '年假天数' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_YEARS_MIN
IS
  '工作年度最小值' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_YEARS_MAX
IS
  '工作年度最大值' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.DAV_STATUS
IS
  '有效标志（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_ANNUAL_VACATION.ALTER_TIME
IS
  '维护时间' ;
  ALTER TABLE BHGMS.BHGMS_D_ANNUAL_VACATION ADD CONSTRAINT PK_BHGMS_D_ANNUAL_VACATION PRIMARY KEY ( DAV_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_APPROVE_NODE
  (
    NODE_ID     CHAR (2 BYTE) CONSTRAINT NN_NODE_ID NOT NULL ,
    NODE_NAME   VARCHAR2 (30 BYTE) ,
    NODE_BTO_ID CHAR (5 BYTE) ,
    NODE_EDITOR CHAR (6 BYTE) ,
    NODE_STATUS CHAR (1 BYTE) DEFAULT '1' ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_APPROVE_NODE
IS
  '流程审批节点代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.NODE_ID
IS
  '流程审批节点代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.NODE_NAME
IS
  '流程审批节点名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.NODE_BTO_ID
IS
  '流程审批节点关联科所代码（12000为全部科所，否则为指定科所）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.NODE_EDITOR
IS
  '操作人员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.NODE_STATUS
IS
  '有效标志（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_NODE.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_D_APPROVE_NODE ON BHGMS.BHGMS_D_APPROVE_NODE
  (
    NODE_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_APPROVE_NODE ADD CONSTRAINT PK_BHGMS_D_APPROVE_NODE PRIMARY KEY ( NODE_ID ) USING INDEX BHGMS.PK_BHGMS_D_APPROVE_NODE ;

CREATE TABLE BHGMS.BHGMS_D_APPROVE_PROCESS
  (
    DAT_ID        CHAR (1 BYTE) NOT NULL ,
    DAP_ID        VARCHAR2 (2 BYTE) NOT NULL ,
    DAN_FIRSTNODE VARCHAR2 (5 BYTE) CONSTRAINT NN_DAN_FIRSTNODE NOT NULL ,
    DAN_CURRNODE  CHAR (2 BYTE) CONSTRAINT NN_DAN_CURRNODE NOT NULL ,
    DAN_PREVNODE  CHAR (2 BYTE) ,
    DAN_NEXTNODE  CHAR (2 BYTE) ,
    DAP_LIMITDAYS NUMBER (2) CONSTRAINT NN_DAN_LIMITDAYS NOT NULL ,
    DAP_ISFINAL   CHAR (1 BYTE) CONSTRAINT NN_DAP_ISFINAL NOT NULL ,
    DAP_EDITOR    VARCHAR2 (6 BYTE) ,
    DAP_STATUS    CHAR (1 BYTE) CONSTRAINT NN_DAP_STATUS NOT NULL ,
    INSERT_TIME   DATE ,
    ALTER_TIME    DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_APPROVE_PROCESS
IS
  '流程审批过程代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAT_ID
IS
  '流程审批类型代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAP_ID
IS
  '流程审批过程节点流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAN_FIRSTNODE
IS
  '流程审批发起节点代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAN_CURRNODE
IS
  '流程审批当前节点代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAN_PREVNODE
IS
  '流程审批上一节点代码（当前节点为发起岗位时为空）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAN_NEXTNODE
IS
  '流程审批下一节点代码（当前节点为终审岗位时为空）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAP_LIMITDAYS
IS
  '流程审批当前节点办结期限' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAP_ISFINAL
IS
  '是否为终审岗位（0-否1-是）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAP_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.DAP_STATUS
IS
  '审批过程状态（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_PROCESS.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_D_APPROVE_PROCESS ON BHGMS.BHGMS_D_APPROVE_PROCESS
  (
    DAP_ID ASC , DAT_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_APPROVE_PROCESS ADD CONSTRAINT PK_BHGMS_D_APPROVE_PROCESS PRIMARY KEY ( DAP_ID, DAT_ID ) USING INDEX BHGMS.PK_BHGMS_D_APPROVE_PROCESS ;

CREATE TABLE BHGMS.BHGMS_D_APPROVE_STATUS
  (
    DAS_ID      CHAR (1 BYTE) CONSTRAINT NN_DAS_ID NOT NULL ,
    DAS_NAME    VARCHAR2 (20 BYTE) ,
    DAS_EDITOR  VARCHAR2 (6 BYTE) ,
    DAS_STATUS  CHAR (1 BYTE) DEFAULT '1' ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE DEFAULT SYSDATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_APPROVE_STATUS
IS
  '流程审批状态代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.DAS_ID
IS
  '流程审批状态代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.DAS_NAME
IS
  '流程审批状态名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.DAS_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.DAS_STATUS
IS
  '有效标志（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_STATUS.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_D_APPROVE_STATUS ON BHGMS.BHGMS_D_APPROVE_STATUS
  (
    DAS_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_APPROVE_STATUS ADD CONSTRAINT PK_BHGMS_D_APPROVE_STATUS PRIMARY KEY ( DAS_ID ) USING INDEX BHGMS.PK_BHGMS_D_APPROVE_STATUS ;

CREATE TABLE BHGMS.BHGMS_D_APPROVE_TYPE
  (
    DAT_ID      CHAR (1 BYTE) CONSTRAINT NN_DAT_ID NOT NULL ,
    DAT_NAME    VARCHAR2 (50 BYTE) ,
    DAT_EDITOR  VARCHAR2 (6 BYTE) ,
    DAT_STATUS  CHAR (1 BYTE) DEFAULT '1' ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_APPROVE_TYPE
IS
  '流程审批类型代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.DAT_ID
IS
  '流程审批类型代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.DAT_NAME
IS
  '流程审批类型名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.DAT_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.DAT_STATUS
IS
  '有效标志（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_APPROVE_TYPE.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_D_APPROVE_TYPE ON BHGMS.BHGMS_D_APPROVE_TYPE
  (
    DAT_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_APPROVE_TYPE ADD CONSTRAINT PK_BHGMS_D_APPROVE_TYPE PRIMARY KEY ( DAT_ID ) USING INDEX BHGMS.PK_BHGMS_D_APPROVE_TYPE ;

CREATE TABLE BHGMS.BHGMS_D_CHANGE_CONTENT
  (
    DCC_ID      VARCHAR2 (2 BYTE) NOT NULL ,
    DCC_NAME    VARCHAR2 (30 BYTE) ,
    DCC_TABLE   VARCHAR2 (30 BYTE) ,
    DCC_EDITOR  CHAR (6 BYTE) ,
    DCC_STATUS  CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  LOGGING ;
ALTER TABLE BHGMS.BHGMS_D_CHANGE_CONTENT ADD CONSTRAINT PK_BHGMS_D_CHANGE_CONTENT PRIMARY KEY ( DCC_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_CHANGE_CONTENT_SUB
  (
    DCCS_ID     VARCHAR2 (2 BYTE) NOT NULL ,
    DCCS_NAME   VARCHAR2 (30 BYTE) ,
    DCC_ID      VARCHAR2 (2 BYTE) NOT NULL ,
    DCCS_EDITOR CHAR (6 BYTE) ,
    DCCS_STATUS CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  LOGGING ;
ALTER TABLE BHGMS.BHGMS_D_CHANGE_CONTENT_SUB ADD CONSTRAINT PK_BHGMS_DCCS PRIMARY KEY ( DCC_ID, DCCS_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_CHECKIN_STATUS
  (
    DCS_ID      CHAR (1 BYTE) NOT NULL ,
    DCS_NAME    VARCHAR2 (20 BYTE) ,
    DCS_EDITOR  VARCHAR2 (6 BYTE) ,
    DCS_STATUS  CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_CHECKIN_STATUS
IS
  '签到状态代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.DCS_ID
IS
  '签到状态代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.DCS_NAME
IS
  '签到状态名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.DCS_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.DCS_STATUS
IS
  '有效标志（1-有效0-无效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_CHECKIN_STATUS.ALTER_TIME
IS
  '修改时间' ;
  ALTER TABLE BHGMS.BHGMS_D_CHECKIN_STATUS ADD CONSTRAINT BHGMS_D_CHECKIN_STATUS_PK PRIMARY KEY ( DCS_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_INTIME
  (
    DIT_ID        VARCHAR2 (2 BYTE) CONSTRAINT NN_DIT_ID NOT NULL ,
    BTO_CATEGORY  CHAR (1 BYTE) ,
    DIT_DAYOFWEEK CHAR (1 BYTE) ,
    DIT_TYPE      CHAR (1 BYTE) ,
    DIT_TIMESTAMP CHAR (4 BYTE) ,
    DIT_ISSUMMER  CHAR (1 BYTE) DEFAULT '0' ,
    DIT_EDITOR    VARCHAR2 (6 BYTE) ,
    DIT_STATUS    CHAR (1 BYTE) DEFAULT '1' ,
    INSERT_TIME   DATE ,
    ALTER_TIME    DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_ID
IS
  '到岗时间设定流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.BTO_CATEGORY
IS
  '税务机关类别' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_DAYOFWEEK
IS
  '星期（1至7表示周一至周日）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_TYPE
IS
  '到岗类型（1-上班2-下班）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_TIMESTAMP
IS
  '到岗时间（四位，如0830和1630）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_ISSUMMER
IS
  '是否为夏时制时间（0-否1-是，默认为0）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.DIT_STATUS
IS
  '有效标志（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_INTIME.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_D_INTIME ON BHGMS.BHGMS_D_INTIME
  (
    DIT_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_INTIME ADD CONSTRAINT PK_BHGMS_D_INTIME PRIMARY KEY ( DIT_ID ) USING INDEX BHGMS.PK_BHGMS_D_INTIME ;

CREATE TABLE BHGMS.BHGMS_D_JOB
  (
    DJ_ID       VARCHAR2 (2 BYTE) NOT NULL ,
    DJ_NAME     VARCHAR2 (30 BYTE) ,
    DJ_EDITOR   VARCHAR2 (6 BYTE) ,
    DJ_STATUS   CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_JOB
IS
  '综合管理系统岗位代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_JOB.DJ_ID
IS
  '综合管理系统岗位代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_JOB.DJ_NAME
IS
  '综合管理系统岗位代码名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_JOB.DJ_STATUS
IS
  '有效标志（1-有效0-无效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_JOB.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_JOB.ALTER_TIME
IS
  '修改时间' ;
  ALTER TABLE BHGMS.BHGMS_D_JOB ADD CONSTRAINT PK_BHGMS_D_JOB PRIMARY KEY ( DJ_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_LEADER_BTO
  (
    DLB_ID         VARCHAR2 (2 BYTE) NOT NULL ,
    LEADER_BTOF_ID CHAR (6 BYTE) ,
    BTO_ID         CHAR (5 BYTE) ,
    DLB_EDITOR     VARCHAR2 (6 BYTE) ,
    DLB_STATUS     CHAR (1 BYTE) ,
    INSERT_TIME    DATE ,
    ALTER_TIME     DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_LEADER_BTO
IS
  '综合管理系统局领导负责科室所代码表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_LEADER_BTO.LEADER_BTOF_ID
IS
  '局领导操作员编号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_LEADER_BTO.BTO_ID
IS
  '税务机关代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_LEADER_BTO.DLB_STATUS
IS
  '有效标志（1-有效0-无效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_LEADER_BTO.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_LEADER_BTO.ALTER_TIME
IS
  '修改时间' ;
  ALTER TABLE BHGMS.BHGMS_D_LEADER_BTO ADD CONSTRAINT PK_BHGMS_D_LEADER_BTO PRIMARY KEY ( DLB_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_RIGHT_MENUITEM
  (
    DRM_ID       VARCHAR2 (4 BYTE) CONSTRAINT NN_RM_ID NOT NULL ,
    DRM_NAME     VARCHAR2 (30 BYTE) ,
    DRM_SUBID    VARCHAR2 (4 BYTE) CONSTRAINT NN_RM_SUBID NOT NULL ,
    DRM_CATEGORY CHAR (1 BYTE) CONSTRAINT NN_RM_CATEGORY NOT NULL ,
    DRM_MENUID   VARCHAR2 (50 BYTE) CONSTRAINT NN_DRM_MENUID NOT NULL ,
    DRM_EDITOR   VARCHAR2 (6 BYTE) ,
    DRM_STATUS   CHAR (1 BYTE) ,
    INSERT_TIME  DATE ,
    ALTER_TIME   DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_ID
IS
  '菜单权限代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_NAME
IS
  '菜单权限名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_SUBID
IS
  '菜单权限上级菜单代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_CATEGORY
IS
  '菜单权限子系统大类' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_MENUID
IS
  '菜单权限对应系统菜单项代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.DRM_STATUS
IS
  '菜单权限状态（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_RIGHT_MENUITEM.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_R_MENUITEM ON BHGMS.BHGMS_D_RIGHT_MENUITEM
  (
    DRM_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_RIGHT_MENUITEM ADD CONSTRAINT PK_R_MENUITEM PRIMARY KEY ( DRM_ID ) USING INDEX BHGMS.PK_R_MENUITEM ;

CREATE TABLE BHGMS.BHGMS_D_RIGHT_SPECITEM
  (
    DRSI_ID     VARCHAR2 (2 BYTE) NOT NULL ,
    DRSI_NAME   VARCHAR2 (30 BYTE) ,
    DRSI_EDITOR CHAR (6 BYTE) ,
    DRSI_STATUS CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_D_RIGHT_SPECITEM
IS
  '综合管理系统特别权限代码表' ;
  ALTER TABLE BHGMS.BHGMS_D_RIGHT_SPECITEM ADD CONSTRAINT PK_BHGMS_D_RIGHT_SPECITEM PRIMARY KEY ( DRSI_ID ) ;

CREATE TABLE BHGMS.BHGMS_D_VACATION_TYPE
  (
    DVT_ID       VARCHAR2 (2 BYTE) CONSTRAINT NN_DVT_ID NOT NULL ,
    DVT_NAME     VARCHAR2 (20 BYTE) ,
    DVT_CATEGORY CHAR (1 BYTE) ,
    DVT_EDITOR   VARCHAR2 (6 BYTE) ,
    DVT_STATUS   CHAR (1 BYTE) ,
    INSERT_TIME  DATE ,
    ALTER_TIME   DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.DVT_ID
IS
  '请假类型代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.DVT_NAME
IS
  '请假类型名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.DVT_CATEGORY
IS
  '请假类型时间分类（1-按时请假2-按天请假3-二者均可）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.DVT_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.DVT_STATUS
IS
  '请假类型状态（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_D_VACATION_TYPE.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_D_VACATION_TYPE ON BHGMS.BHGMS_D_VACATION_TYPE
  (
    DVT_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_D_VACATION_TYPE ADD CONSTRAINT PK_D_VACATION_TYPE PRIMARY KEY ( DVT_ID ) USING INDEX BHGMS.PK_D_VACATION_TYPE ;

CREATE TABLE BHGMS.BHGMS_F_APPROVE
  (
    FA_ID            VARCHAR2 (8 BYTE) CONSTRAINT NN_FA_ID NOT NULL ,
    FA_NAME          VARCHAR2 (100 BYTE) CONSTRAINT NN_BFA_FA_NAME NOT NULL ,
    FA_TYPE          CHAR (1 BYTE) CONSTRAINT NN_BFA_FA_TYPE NOT NULL ,
    FA_ISSUER        CHAR (6 BYTE) CONSTRAINT NN_BFA_FA_ISSUER NOT NULL ,
    FA_ISSUER_INFACT CHAR (6 BYTE) ,
    FA_CURRENTUSER   CHAR (6 BYTE) CONSTRAINT NN_BFA_FA_CU NOT NULL ,
    FA_CURRENTNODE   CHAR (2 BYTE) CONSTRAINT NN_BFA_FA_CN NOT NULL ,
    FA_LASTUSER      CHAR (6 BYTE) CONSTRAINT NN_BFA_FA_LASTUSER NOT NULL ,
    FA_ISSUEDATE     DATE CONSTRAINT NN_BFA_FA_ISSUEDATE NOT NULL ,
    FA_FINALDATE     DATE ,
    FA_STATUS        CHAR (1 BYTE) CONSTRAINT NN_BFA_FA_STATUS NOT NULL ,
    INSERT_TIME      DATE ,
    ALTER_TIME       DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_ID
IS
  '流程审批流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_NAME
IS
  '流程审批名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_TYPE
IS
  '流程审批类型（取自D_FA_TYPE）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_ISSUER
IS
  '流程审批发起人' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_ISSUER_INFACT
IS
  '流程审批实际主体' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_CURRENTUSER
IS
  '流程审批当前用户' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_CURRENTNODE
IS
  '流程审批当前环节（取自D_FA_NODE）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_LASTUSER
IS
  '发送人' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_ISSUEDATE
IS
  '发起日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_FINALDATE
IS
  '终审日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.FA_STATUS
IS
  '流程审批状态（取自D_FA_STATUS）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_GMS_F_APPROVE ON BHGMS.BHGMS_F_APPROVE
  (
    FA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_APPROVE ADD CONSTRAINT PK_GMS_F_APPROVE PRIMARY KEY ( FA_ID ) USING INDEX BHGMS.PK_GMS_F_APPROVE ;

CREATE TABLE BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB
  (
    FA_ID              VARCHAR2 (8 BYTE) CONSTRAINT NN_FAOS_FA_ID NOT NULL ,
    FAOS_DESCRIPTION   VARCHAR2 (200 BYTE) ,
    FAOS_ISSUEDATE     DATE CONSTRAINT NN_FAOS_ISSUEDATE NOT NULL ,
    FAOS_BEGINTIME     CHAR (4 BYTE) CONSTRAINT NN_FAOS_BEGINTIME NOT NULL ,
    FAOS_ENDTIME       CHAR (4 BYTE) CONSTRAINT NN_FAOS_ENDTIME NOT NULL ,
    FAOS_OVERTIME_HOUR NUMBER (3) CONSTRAINT NN_FAOS_TIME_HOUR NOT NULL ,
    FAOS_OVERTIME_MIN  NUMBER (2) CONSTRAINT NN_FAOS_TIME_MIN NOT NULL ,
    FAOS_ORIGIN        CHAR (1 BYTE) CONSTRAINT NN_FAOS_ORIGIN NOT NULL ,
    FAOS_ORIGIN_ID     VARCHAR2 (8 BYTE) ,
    INSERT_TIME        DATE ,
    ALTER_TIME         DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB
IS
  '综合管理系统加班流程审批子表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FA_ID
IS
  '流程审批流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_DESCRIPTION
IS
  '加班情况说明，由加班发起人录入' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_ISSUEDATE
IS
  '加班日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_BEGINTIME
IS
  '加班起始时间（发起人录入）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_ENDTIME
IS
  '加班结束时间（发起人录入）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_OVERTIME_HOUR
IS
  '加班时间（小时）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_OVERTIME_MIN
IS
  '加班时间（分钟）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_ORIGIN
IS
  '加班来源（1-晚签到加班2-自行发起加班）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.FAOS_ORIGIN_ID
IS
  '加班来源记录（如请假类型为晚签到请假，取自BHGMS_F_CHECKIN.FC_ID）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_FAOS ON BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB
  (
    FA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB ADD CONSTRAINT PK_BHGMS_FAOS PRIMARY KEY ( FA_ID ) USING INDEX BHGMS.PK_BHGMS_FAOS ;

CREATE TABLE BHGMS.BHGMS_F_APPROVE_PROCESS
  (
    FAP_ID        VARCHAR2 (10 BYTE) CONSTRAINT NN_FAP_ID NOT NULL ,
    FA_ID         VARCHAR2 (8 BYTE) NOT NULL ,
    FAP_NODE_NOW  CHAR (2 BYTE) CONSTRAINT NN_FAP_NODE_NOW NOT NULL ,
    FAP_USER_NOW  CHAR (6 BYTE) CONSTRAINT NN_FAP_USER_NOW NOT NULL ,
    FAP_NODE_NEXT CHAR (2 BYTE) ,
    FAP_USER_NEXT CHAR (6 BYTE) ,
    FAP_CONTROL   CHAR (1 BYTE) CONSTRAINT NN_FAP_CONTROL NOT NULL ,
    FAP_COMMENT   VARCHAR2 (200 BYTE) ,
    FAP_DATE      DATE DEFAULT SYSDATE CONSTRAINT NN_FAP_DATE NOT NULL ,
    INSERT_TIME   DATE ,
    ALTER_TIME    DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_ID
IS
  '流程审批过程流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FA_ID
IS
  '流程审批流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_NODE_NOW
IS
  '流程审批过程当前节点' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_USER_NOW
IS
  '流程审批过程当前操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_NODE_NEXT
IS
  '流程审批过程下一节点' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_USER_NEXT
IS
  '流程审批过程下一操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_CONTROL
IS
  '当前节点操作（0-发送至下一岗位1-终审通过2-退回至上一岗位3-退回至发起岗位4-终审不通过）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_COMMENT
IS
  '审批意见' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.FAP_DATE
IS
  '流程审批过程操作日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_PROCESS.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_F_APPROVE_PROCESS ON BHGMS.BHGMS_F_APPROVE_PROCESS
  (
    FAP_ID ASC , FA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_APPROVE_PROCESS ADD CONSTRAINT PK_BHGMS_F_APPROVE_PROCESS PRIMARY KEY ( FAP_ID, FA_ID ) USING INDEX BHGMS.PK_BHGMS_F_APPROVE_PROCESS ;

CREATE TABLE BHGMS.BHGMS_F_APPROVE_VACATION_SUB
  (
    FA_ID              VARCHAR2 (8 BYTE) CONSTRAINT NN_FAVS_FA_ID NOT NULL ,
    FAVS_TIME_TYPE     CHAR (1 BYTE) CONSTRAINT NN_FAVS_TIME_TYPE NOT NULL ,
    FAVS_DESCRIPTION   VARCHAR2 (200 BYTE) ,
    FAVS_ISSUEDATE     DATE CONSTRAINT NN_FAVS_ISSUEDATE NOT NULL ,
    FAVS_ENDDATE       DATE ,
    FAVS_BEGINTIME     CHAR (4 BYTE) ,
    FAVS_ENDTIME       CHAR (4 BYTE) ,
    FAVS_VACATION_HOUR NUMBER (3) CONSTRAINT NN_FAVS_VACATION_HOUR NOT NULL ,
    FAVS_VACATION_MIN  NUMBER (2) CONSTRAINT NN_FAVS_VACATION_MIN NOT NULL ,
    FAVS_TYPE          VARCHAR2 (2 BYTE) CONSTRAINT NN_FAVS_TYPE NOT NULL ,
    FAVS_ORIGIN        CHAR (1 BYTE) CONSTRAINT NN_FAVS_ORIGIN NOT NULL ,
    FAVS_ORIGIN_ID     VARCHAR2 (8 BYTE) ,
    INSERT_TIME        DATE ,
    ALTER_TIME         DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FA_ID
IS
  '流程审批流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_TIME_TYPE
IS
  '请假时间类型（1-按时间请假2-按天请假）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_DESCRIPTION
IS
  '请假情况说明，由请假发起人录入' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_ISSUEDATE
IS
  '请假日期（当FAVS_TIME_TYPE为2时为请假起始日期）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_ENDDATE
IS
  '请假结束日期（当FAVS_TIME_TYPE为2时使用，1时为空）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_BEGINTIME
IS
  '请假起始时间（四位）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_ENDTIME
IS
  '请假结束时间（发起人录入）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_VACATION_HOUR
IS
  '请假时间（小时）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_VACATION_MIN
IS
  '请假时间（分钟）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_TYPE
IS
  '请假类型（取自D_VACATION_TYPE）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_ORIGIN
IS
  '请假来源（1-迟到请假2-自行发起请假）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.FAVS_ORIGIN_ID
IS
  '请假来源记录（如请假类型为迟到请假，取自BHGMS_F_CHECKIN.FC_ID）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_APPROVE_VACATION_SUB.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_FAVS ON BHGMS.BHGMS_F_APPROVE_VACATION_SUB
  (
    FA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_APPROVE_VACATION_SUB ADD CONSTRAINT PK_BHGMS_FAVS PRIMARY KEY ( FA_ID ) USING INDEX BHGMS.PK_BHGMS_FAVS ;

CREATE TABLE BHGMS.BHGMS_F_CHECKIN
  (
    FC_ID        VARCHAR2 (8 BYTE) NOT NULL ,
    FC_DATE      CHAR (8 BYTE) NOT NULL ,
    FC_TYPE      CHAR (1 BYTE) NOT NULL ,
    FC_CHECKER   CHAR (6 BYTE) NOT NULL ,
    FC_CHECKTIME CHAR (4 BYTE) ,
    FC_STATUS    CHAR (1 BYTE) ,
    INSERT_TIME  DATE ,
    ALTER_TIME   DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_ID
IS
  '到岗签到流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_DATE
IS
  '签到日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_TYPE
IS
  '签到类型（0-上班1-下班）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_CHECKER
IS
  '签到人' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_CHECKTIME
IS
  '签到时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.FC_STATUS
IS
  '签到状态（0-准时到岗1-迟到2-迟到保留代码3-准时下班4-早退5-加班6-早退保留代码7-加班保留代码）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_CHECKIN.ALTER_TIME
IS
  '修改时间' ;
  CREATE INDEX BHGMS.IDX_BHGMS_F_CHECKIN_PK ON BHGMS.BHGMS_F_CHECKIN
    (
      FC_ID ASC
    )
    TABLESPACE USERS LOGGING ;
CREATE UNIQUE INDEX BHGMS.IDX_BHGMS_F_CHECKIN_UNI ON BHGMS.BHGMS_F_CHECKIN
  (
    FC_DATE ASC , FC_TYPE ASC , FC_CHECKER ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_CHECKIN ADD CONSTRAINT PK_BHGMS_F_CHECKIN PRIMARY KEY ( FC_ID ) USING INDEX BHGMS.IDX_BHGMS_F_CHECKIN_PK ;

CREATE TABLE BHGMS.BHGMS_F_VACATION_LIST
  (
    FVL_ID        VARCHAR2 (8 BYTE) NOT NULL ,
    FVL_ISSUER    CHAR (5 BYTE) CONSTRAINT NN_FVL_ISSUER NOT NULL ,
    FVL_TIME_TYPE CHAR (1 BYTE) CONSTRAINT NN_FVL_TIME_TYPE NOT NULL ,
    FVL_BEGINDATE DATE CONSTRAINT NN_FVL_BEGINDATE NOT NULL ,
    FVL_ENDDATE   DATE ,
    FVL_BEGINTIME CHAR (4 BYTE) ,
    FVL_ENDTIME   CHAR (4 BYTE) ,
    INSERT_TIME   DATE ,
    ALTER_TIME    DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_ID
IS
  '请假列表流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_ISSUER
IS
  '请假人' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_TIME_TYPE
IS
  '请假时间类型（1-按时请假2-按天请假）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_BEGINDATE
IS
  '请假起始日期（当类型为按时请假时为请假日期）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_ENDDATE
IS
  '请假结束日期' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_BEGINTIME
IS
  '请假起始时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.FVL_ENDTIME
IS
  '请假结束时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_F_VACATION_LIST.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_F_VACATION_LIST ON BHGMS.BHGMS_F_VACATION_LIST
  (
    FVL_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_F_VACATION_LIST ADD CONSTRAINT PK_BHGMS_F_VACATION_LIST PRIMARY KEY ( FVL_ID ) USING INDEX BHGMS.PK_BHGMS_F_VACATION_LIST ;

CREATE TABLE BHGMS.BHGMS_H_APPROVE
  (
    HA_ID       VARCHAR2 (8 BYTE) NOT NULL ,
    FA_ID       VARCHAR2 (8 BYTE) ,
    HA_TYPE     CHAR (1 BYTE) ,
    HA_EDITOR   CHAR (6 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_H_APPROVE
IS
  '流程审批历史表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.HA_ID
IS
  '流程审批历史表流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.FA_ID
IS
  '流程审批流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.HA_TYPE
IS
  '流程审批历史表操作类型（0-变更1-删除，为变更时在子表记录变更名明细）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.HA_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_H_APPROVE ON BHGMS.BHGMS_H_APPROVE
  (
    HA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_H_APPROVE ADD CONSTRAINT PK_BHGMS_H_APPROVE PRIMARY KEY ( HA_ID ) USING INDEX BHGMS.PK_BHGMS_H_APPROVE ;

CREATE TABLE BHGMS.BHGMS_H_APPROVE_VACATION_SUB
  (
    HA_ID             VARCHAR2 (8 BYTE) NOT NULL ,
    HAVS_ID           VARCHAR2 (2 BYTE) NOT NULL ,
    HAVS_ALTER        VARCHAR2 (2 BYTE) ,
    HAVS_PREV_CONTENT VARCHAR2 (200 BYTE) ,
    HAVS_POST_CONTENT VARCHAR2 (200 BYTE) ,
    INSERT_TIME       DATE ,
    ALTER_TIME        DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_H_APPROVE_VACATION_SUB
IS
  '流程审批历史表请假子表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.HA_ID
IS
  '流程审批历史表流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.HAVS_ID
IS
  '流程审批历史表请假子表流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.HAVS_ALTER
IS
  '变更项目' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.HAVS_PREV_CONTENT
IS
  '变更前内容' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.HAVS_POST_CONTENT
IS
  '变更后内容' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_APPROVE_VACATION_SUB.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_H_APPROVE_VACATION_SUB ON BHGMS.BHGMS_H_APPROVE_VACATION_SUB
  (
    HA_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_H_APPROVE_VACATION_SUB ADD CONSTRAINT PK_H_APPROVE_VACATION_SUB PRIMARY KEY ( HA_ID, HAVS_ID ) USING INDEX BHGMS.PK_H_APPROVE_VACATION_SUB ;

CREATE TABLE BHGMS.BHGMS_H_DIMENSION
  (
    HD_ID           VARCHAR2 (8 BYTE) NOT NULL ,
    HD_CC_ID        VARCHAR2 (2 BYTE) CONSTRAINT NN_HD_CHANGED_CONTENT NOT NULL ,
    HD_CCS_ID       VARCHAR2 (2 BYTE) ,
    HD_TYPE         CHAR (1 BYTE) ,
    HD_PREV_CONTENT VARCHAR2 (30 BYTE) ,
    HD_POST_CONTENT VARCHAR2 (30 BYTE) ,
    HD_EDITOR       CHAR (6 BYTE) ,
    INSERT_TIME     DATE ,
    ALTER_TIME      DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_H_DIMENSION
IS
  '综合管理系统代码历史表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_ID
IS
  '综合管理系统代码历史表流水号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_CC_ID
IS
  '代码表大类' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_CCS_ID
IS
  '代码表小类' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_TYPE
IS
  '代码表操作类型（0-变更1-删除-2新增）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_PREV_CONTENT
IS
  '代码表变更前内容（如变更类型为修改或删除则为修改前或被删除的内容，如变更类型为新增则为空）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_POST_CONTENT
IS
  '代码表变更后内容（如变更类型为修改则为修改后的内容，如变更类型为新增则为新增内容，类型为删除则为空）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.HD_EDITOR
IS
  '操作员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_H_DIMENSION.ALTER_TIME
IS
  '修改时间' ;
CREATE UNIQUE INDEX BHGMS.PK_BHGMS_H_DIMENSION ON BHGMS.BHGMS_H_DIMENSION
  (
    HD_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_H_DIMENSION ADD CONSTRAINT PK_BHGMS_H_DIMENSION PRIMARY KEY ( HD_ID ) USING INDEX BHGMS.PK_BHGMS_H_DIMENSION ;

CREATE TABLE BHGMS.BHGMS_R_MENUGROUP
  (
    RM_ID       VARCHAR2 (3 BYTE) NOT NULL ,
    RM_NAME     VARCHAR2 (40 BYTE) ,
    RM_EDITOR   VARCHAR2 (6 BYTE) ,
    RM_STATUS   CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_R_MENUGROUP.RM_EDITOR
IS
  '操作员' ;
CREATE UNIQUE INDEX BHGMS.PK_R_MENUGROUP ON BHGMS.BHGMS_R_MENUGROUP
  (
    RM_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP ADD CONSTRAINT PK_R_MENUGROUP PRIMARY KEY ( RM_ID ) USING INDEX BHGMS.PK_R_MENUGROUP ;

CREATE TABLE BHGMS.BHGMS_R_MENUGROUP_OFFICER
  (
    RMOF_ID     VARCHAR2 (3 BYTE) NOT NULL ,
    RMOF_RMID   VARCHAR2 (3 BYTE) NOT NULL ,
    RMOF_BTOFID CHAR (6 BYTE) NOT NULL ,
    RMOF_EDITOR VARCHAR2 (6 BYTE) ,
    RMOF_STATUS CHAR (1 BYTE) NOT NULL ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
CREATE UNIQUE INDEX BHGMS.PK_R_MENUGROUP_OFFICER ON BHGMS.BHGMS_R_MENUGROUP_OFFICER
  (
    RMOF_ID ASC
  )
  TABLESPACE USERS LOGGING ;
CREATE UNIQUE INDEX BHGMS.UNI_R_MENUGROUP_OFFICER ON BHGMS.BHGMS_R_MENUGROUP_OFFICER
  (
    RMOF_STATUS ASC , RMOF_RMID ASC , RMOF_BTOFID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_OFFICER ADD CONSTRAINT PK_R_MENUGROUP_OFFICER PRIMARY KEY ( RMOF_ID ) USING INDEX BHGMS.PK_R_MENUGROUP_OFFICER ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_OFFICER ADD CONSTRAINT UNI_R_MENUGROUP_OFFICER UNIQUE ( RMOF_STATUS , RMOF_RMID , RMOF_BTOFID ) USING INDEX BHGMS.UNI_R_MENUGROUP_OFFICER ;

CREATE TABLE BHGMS.BHGMS_R_MENUGROUP_ORGAN
  (
    RMO_ID      VARCHAR2 (3 BYTE) NOT NULL ,
    RMO_RMID    VARCHAR2 (3 BYTE) NOT NULL ,
    RMO_BTOID   CHAR (5 BYTE) NOT NULL ,
    RMO_EDITOR  VARCHAR2 (6 BYTE) ,
    RMO_STATUS  CHAR (1 BYTE) NOT NULL ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_R_MENUGROUP_ORGAN.RMO_EDITOR
IS
  '操作员' ;
CREATE UNIQUE INDEX BHGMS.PK_R_MENUGROUP_ORGAN ON BHGMS.BHGMS_R_MENUGROUP_ORGAN
  (
    RMO_ID ASC
  )
  TABLESPACE USERS LOGGING ;
CREATE UNIQUE INDEX BHGMS.UNI_R_MENUGROUP_ORGAN ON BHGMS.BHGMS_R_MENUGROUP_ORGAN
  (
    RMO_STATUS ASC , RMO_RMID ASC , RMO_BTOID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_ORGAN ADD CONSTRAINT PK_R_MENUGROUP_ORGAN PRIMARY KEY ( RMO_ID ) USING INDEX BHGMS.PK_R_MENUGROUP_ORGAN ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_ORGAN ADD CONSTRAINT UNI_R_MENUGROUP_ORGAN UNIQUE ( RMO_STATUS , RMO_RMID , RMO_BTOID ) USING INDEX BHGMS.UNI_R_MENUGROUP_ORGAN ;

CREATE TABLE BHGMS.BHGMS_R_MENUGROUP_SUB
  (
    RM_ID       VARCHAR2 (3 BYTE) NOT NULL ,
    RMS_ID      VARCHAR2 (2 BYTE) NOT NULL ,
    RMS_MENUID  VARCHAR2 (4 BYTE) ,
    RMS_EDITOR  VARCHAR2 (6 BYTE) ,
    RMS_STATUS  CHAR (1 BYTE) ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
CREATE UNIQUE INDEX BHGMS.PK_R_MENUGROUP_SUB ON BHGMS.BHGMS_R_MENUGROUP_SUB
  (
    RM_ID ASC , RMS_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_SUB ADD CONSTRAINT PK_R_MENUGROUP_SUB PRIMARY KEY ( RM_ID, RMS_ID ) USING INDEX BHGMS.PK_R_MENUGROUP_SUB ;

CREATE TABLE BHGMS.BHGMS_R_NODE_JOB
  (
    RNJ_ID      VARCHAR2 (3 BYTE) NOT NULL ,
    RNJ_NODEID  CHAR (2 BYTE) NOT NULL ,
    RNJ_TYPE    CHAR (1 BYTE) NOT NULL ,
    RNJ_JOBID   VARCHAR2 (2 BYTE) ,
    RNJ_BTOFID  CHAR (6 BYTE) ,
    RNJ_EDITOR  VARCHAR2 (6 BYTE) ,
    RNJ_STATUS  CHAR (1 BYTE) NOT NULL ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_R_NODE_JOB.RNJ_EDITOR
IS
  '操作员' ;
CREATE UNIQUE INDEX BHGMS.PK_R_NODE_JOB ON BHGMS.BHGMS_R_NODE_JOB
  (
    RNJ_ID ASC
  )
  TABLESPACE USERS LOGGING ;
  ALTER TABLE BHGMS.BHGMS_R_NODE_JOB ADD CONSTRAINT PK_R_NODE_JOB PRIMARY KEY ( RNJ_ID ) USING INDEX BHGMS.PK_R_NODE_JOB ;

CREATE TABLE BHGMS.BHGMS_U_LOGIN
  (
    BTOF_ID     VARCHAR2 (6 BYTE) CONSTRAINT NN_U_LOGIN_BTOF_ID NOT NULL ,
    PASSWORD    VARCHAR2 (64 BYTE) CONSTRAINT NN_U_LOGIN_PWD NOT NULL ,
    STATUS      CHAR (1 BYTE) DEFAULT '1' CONSTRAINT NN_U_LOGIN_STATUS NOT NULL ,
    INSERT_TIME DATE ,
    ALTER_TIME  DATE
  )
  TABLESPACE USERS LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_U_LOGIN.BTOF_ID
IS
  '操作员编号' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_LOGIN.PASSWORD
IS
  '密码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_LOGIN.STATUS
IS
  '用户状态（0-无效1-有效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_LOGIN.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_LOGIN.ALTER_TIME
IS
  '修改时间' ;
  ALTER TABLE BHGMS.BHGMS_U_LOGIN ADD CONSTRAINT PK_BHGMS_U_LOGIN PRIMARY KEY ( BTOF_ID ) ;

CREATE TABLE BHGMS.BHGMS_U_OFFICER
  (
    BTOF_ID        CHAR (6 BYTE) NOT NULL ,
    BTOF_NAME      VARCHAR2 (50 BYTE) ,
    BTO_ID         CHAR (5 BYTE) ,
    JOB_ID         VARCHAR2 (2 BYTE) ,
    BTOF_ISUNI     CHAR (1 BYTE) ,
    BTOF_YEARS     NUMBER (2) ,
    BTOF_IPADDRESS VARCHAR2 (15 BYTE) ,
    BTOF_MAC       CHAR (17 BYTE) ,
    BTOF_EDITOR    VARCHAR2 (6 BYTE) ,
    BTOF_STATUS    CHAR (1 BYTE) ,
    INSERT_TIME    DATE ,
    ALTER_TIME     DATE
  )
  LOGGING ;
COMMENT ON TABLE BHGMS.BHGMS_U_OFFICER
IS
  '综合管理系统税务官员表' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_ID
IS
  '综合管理系统税务官员代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_NAME
IS
  '综合管理系统税务官员姓名' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTO_ID
IS
  '综合管理系统税务官员所属税务机关' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.JOB_ID
IS
  '综合管理系统税务官员岗位' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_ISUNI
IS
  '是否为唯一领导（1-是0-否，本部门只有一名副科长时设置）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_YEARS
IS
  '综合管理系统税务官员工作时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_IPADDRESS
IS
  '操作员IP地址' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_MAC
IS
  '操作员MAC地址' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_EDITOR
IS
  '操作人员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.BTOF_STATUS
IS
  '有效标志（1-有效0-无效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_OFFICER.ALTER_TIME
IS
  '修改时间' ;
  ALTER TABLE BHGMS.BHGMS_U_OFFICER ADD CONSTRAINT PK_BHGMS_U_OFFICER PRIMARY KEY ( BTOF_ID ) ;

CREATE TABLE BHGMS.BHGMS_U_ORGAN
  (
    BTO_ID       CHAR (5 BYTE) NOT NULL ,
    BTO_NAME     VARCHAR2 (60 BYTE) ,
    BTO_CATEGORY CHAR (1 BYTE) ,
    BTO_EDITOR   VARCHAR2 (6 BYTE) ,
    BTO_STATUS   CHAR (1 BYTE) ,
    INSERT_TIME  DATE ,
    ALTER_TIME   DATE
  )
  LOGGING ;
COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.BTO_ID
IS
  '综合管理系统税务机关代码' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.BTO_NAME
IS
  '综合管理系统税务机关名称' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.BTO_CATEGORY
IS
  '综合管理系统税务机关类型' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.BTO_EDITOR
IS
  '操作人员' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.BTO_STATUS
IS
  '有效标志（1-有效0-无效）' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.INSERT_TIME
IS
  '录入时间' ;
  COMMENT ON COLUMN BHGMS.BHGMS_U_ORGAN.ALTER_TIME
IS
  '维护时间' ;
  ALTER TABLE BHGMS.BHGMS_U_ORGAN ADD CONSTRAINT PK_BHGMS_U_ORGAN PRIMARY KEY ( BTO_ID ) ;

ALTER TABLE BHGMS.BHGMS_F_APPROVE_OVERTIME_SUB ADD CONSTRAINT FK_F_APPROVE_OVERTIME_SUB FOREIGN KEY ( FA_ID ) REFERENCES BHGMS.BHGMS_F_APPROVE ( FA_ID ) NOT DEFERRABLE ;

ALTER TABLE BHGMS.BHGMS_F_APPROVE_PROCESS ADD CONSTRAINT FK_F_APPROVE_PROCESS_SUB FOREIGN KEY ( FA_ID ) REFERENCES BHGMS.BHGMS_F_APPROVE ( FA_ID ) NOT DEFERRABLE ;

ALTER TABLE BHGMS.BHGMS_F_APPROVE_VACATION_SUB ADD CONSTRAINT FK_F_APPROVE_VACATION_SUB FOREIGN KEY ( FA_ID ) REFERENCES BHGMS.BHGMS_F_APPROVE ( FA_ID ) NOT DEFERRABLE ;

ALTER TABLE BHGMS.BHGMS_H_APPROVE_VACATION_SUB ADD CONSTRAINT FK_H_APPROVE_VACATION_SUB FOREIGN KEY ( HA_ID ) REFERENCES BHGMS.BHGMS_H_APPROVE ( HA_ID ) NOT DEFERRABLE ;

ALTER TABLE BHGMS.BHGMS_R_MENUGROUP_SUB ADD CONSTRAINT FK_R_MENUGROUP_SUB FOREIGN KEY ( RM_ID ) REFERENCES BHGMS.BHGMS_R_MENUGROUP ( RM_ID ) NOT DEFERRABLE ;


-- Oracle SQL Developer Data Modeler 概要报告: 
-- 
-- CREATE TABLE                            31
-- CREATE INDEX                            24
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
